// Deploys the Azure Storage Account that holds Terraform remote state (azurerm backend).
// Kept outside Terraform on purpose so `terraform destroy` can never remove its own backend
// (docs/terraform-best-practices.md, "Option B").
//
// Deploy:
//   az deployment sub create \
//     --location westeurope \
//     --template-file infrastructure/bicep/main.bicep \
//     --parameters applicationName=alz environmentName=dev environmentNumber=1 \
//                  uniqueIdentifier=<13-char-id> \
//                  allowedIpAddresses="['203.0.113.10']" \
//                  terraformApplyPrincipalId=<apply-object-id> \
//                  terraformPlanPrincipalId=<plan-object-id>

targetScope = 'subscription'

// Storage account name budget (24): 'st'(2) + applicationName(5) + environmentName(3) + environmentNumber(1) + uniqueIdentifier(13).
@description('Application name used in resource names and tags. Lowercase letters and digits only.')
@minLength(1)
@maxLength(5)
param applicationName string = 'alz'

@description('Environment name used in resource names and tags. Lowercase letters and digits only.')
@minLength(1)
@maxLength(3)
param environmentName string = 'dev'

@description('Environment instance number (single digit).')
@minValue(1)
@maxValue(9)
param environmentNumber int = 1

@description('Required 13-character unique identifier (lowercase letters and digits) that makes the storage account name globally unique. Generated by the tfstate-infrastructure-deploy and tfstate-infrastructure-plan workflows.')
@minLength(13)
@maxLength(13)
param uniqueIdentifier string

@description('Azure region for the resource group and storage account.')
param location string = deployment().location

@description('Name of the resource group to create for Terraform state.')
param resourceGroupName string = 'rg-${applicationName}-tfstate-${environmentName}-${environmentNumber}'

@description('Globally unique storage account name (3-24 lowercase letters and digits).')
@minLength(3)
@maxLength(24)
param storageAccountName string = toLower('st${applicationName}${environmentName}${environmentNumber}${uniqueIdentifier}')

@description('Replication SKU. GZRS is recommended; fall back to ZRS/GRS where GZRS is unavailable.')
@allowed([
  'Standard_GZRS'
  'Standard_RAGZRS'
  'Standard_ZRS'
  'Standard_GRS'
  'Standard_LRS'
])
param skuName string = 'Standard_GZRS'

@description('Blob containers to create for state, one per stack/landing zone.')
param containerNames array = [
  'tfstate'
]

@description('Enabled allows access from allowedIpAddresses only; Disabled requires a private endpoint.')
@allowed([
  'Enabled'
  'Disabled'
])
param publicNetworkAccess string = 'Enabled'

@description('Deny limits access to allowedIpAddresses; Allow accepts any source and leaves Entra ID + RBAC as the only control (shared keys are disabled). Use Deny once CI has a stable egress IP.')
@allowed([
  'Allow'
  'Deny'
])
param networkDefaultAction string = 'Deny'

@description('Public IPv4 addresses or CIDR ranges allowed through the firewall (e.g. your workstation or runner egress). Ignored when networkDefaultAction is Allow.')
param allowedIpAddresses array = []

@description('Days to keep soft-deleted blobs and containers.')
@minValue(7)
@maxValue(365)
param softDeleteRetentionDays int = 90

@description('Point-in-time restore window in days. Must be lower than softDeleteRetentionDays.')
@minValue(1)
@maxValue(364)
param restorePolicyDays int = 30

@description('Object ID of the identity that runs terraform apply; granted Storage Blob Data Contributor on each container, and on the storage account Storage Account Contributor plus Role Based Access Control Administrator (limited to assigning Storage Account Backup Contributor). Leave empty to skip.')
param terraformApplyPrincipalId string = ''

@description('Principal type of terraformApplyPrincipalId.')
@allowed([
  'ServicePrincipal'
  'User'
  'Group'
])
param terraformApplyPrincipalType string = 'ServicePrincipal'

@description('Object ID of the identity that runs terraform plan; granted Storage Blob Data Reader on each container. Leave empty to skip.')
param terraformPlanPrincipalId string = ''

@description('Principal type of terraformPlanPrincipalId.')
@allowed([
  'ServicePrincipal'
  'User'
  'Group'
])
param terraformPlanPrincipalType string = 'ServicePrincipal'

@description('Object ID of the local (act) identity that runs both terraform plan and apply; granted Storage Blob Data Contributor on each container. Leave empty to skip.')
param terraformLocalPrincipalId string = ''

@description('Principal type of terraformLocalPrincipalId.')
@allowed([
  'ServicePrincipal'
  'User'
  'Group'
])
param terraformLocalPrincipalType string = 'User'

@description('Apply a CanNotDelete lock to the resource group.')
param enableDeleteLock bool = true

param tags object = {
  application: applicationName
  environment: environmentName
  environmentNumber: string(environmentNumber)
  workload: 'terraform-state'
  managedBy: 'bicep'
}

resource rg 'Microsoft.Resources/resourceGroups@2024-03-01' = {
  name: resourceGroupName
  location: location
  tags: tags
}

module storage 'modules/storage.bicep' = {
  name: 'tfstate-storage'
  scope: rg
  params: {
    location: location
    storageAccountName: storageAccountName
    skuName: skuName
    containerNames: containerNames
    publicNetworkAccess: publicNetworkAccess
    networkDefaultAction: networkDefaultAction
    allowedIpAddresses: allowedIpAddresses
    softDeleteRetentionDays: softDeleteRetentionDays
    restorePolicyDays: restorePolicyDays
    terraformApplyPrincipalId: terraformApplyPrincipalId
    terraformApplyPrincipalType: terraformApplyPrincipalType
    terraformPlanPrincipalId: terraformPlanPrincipalId
    terraformPlanPrincipalType: terraformPlanPrincipalType
    terraformLocalPrincipalId: terraformLocalPrincipalId
    terraformLocalPrincipalType: terraformLocalPrincipalType
    enableDeleteLock: enableDeleteLock
    tags: tags
  }
}

output resourceGroupName string = rg.name
output storageAccountName string = storage.outputs.storageAccountName
output containerNames array = containerNames
output blobEndpoint string = storage.outputs.blobEndpoint
